PROD_DICT = {
    "Natural Resources": [
        "amaiz",
        "arice",
        "aocer",
        "aoils",
        "aroot",
        "avege",
        "asugr",
        "atoba",
        "acoff",
        "afrui",
        "acoff",
        "aocrp",
        "acatt",
        "apoul",
        "aoliv",
        "afore",
        "afish",
        "amine",
        "awatr",
    ],
    "Electricity": ["aelec"],
    "Construction, Trade, Services": [
        "acons",
        "atrad",
        "atran",
        "ahotl",
        "acomm",
        "afsrv",
        "areal",
        "absrv",
        "apadm",
        "aeduc",
        "aheal",
        "aosrv",
    ],
    "Manufacturing": [
        "afood",
        "abeve",
        "atext",
        "awood",
        "achem",
        "anmet",
        "ametl",
        "amach",
        "aoman",
    ],
}